<?php
// +----------------------------------------------------------------------
// | ThinkPHP [ WE CAN DO IT JUST THINK ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006~2016 http://thinkphp.cn All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: liu21st <liu21st@gmail.com>
// +----------------------------------------------------------------------
// $Id$

return [
    // 生成运行时目录
    '__dir__'  => ['runtime/cache', 'runtime/log', 'runtime/temp'],
    '__file__' => ['tags.php'],

    // 定义index模块的自动生成
    // onethink生成
    'admin'    => [
        '__file__'   => ['tags.php', 'config.php', 'common.php'],
        '__dir__'    => ['behavior', 'controller', 'model', 'logic', 'view'],
        'controller' => [
            'Action',
            'Addons',
            'Admin',
            'Article',
            'Attribute',
            'Content',
            'AuthManager',
            'Category',
            'Channel',
            'Config',
            'Databases',
            'File',
            'Index',
            'Memu',
            'Model',
            'Public',
            'Qiniu',
            'Think',
            'Update',
            'User'
        ],
        'model'      => [
            'Action',
            'Addons',
            'Attribute',
            'Article',
            'AuthGroup',
            'AuthRule',
            'Category',
            'Channel',
            'Config',
            'Document',
            'File',
            'Hooks',
            'Member',
            'Memu',
            'Model',
            'Picture',
            'Url'
        ],
        'logic'      => ['Article', 'Base', 'Download'],
        'view'       => [
            'action/actionlog',
            'action/edit',
            'addons/adminlist',
            'addons/config',
            'addons/create',
            'addons/edit',
            'addons/edithook',
            'addons/hooks',
            'addons/index',
            'article/add',
            'article/batchoperate',
            'article/draftbox',
            'article/edit',
            'article/examine',
            'article/index',
            'article/mydocument',
            'article/recycle',
            'article/sidemenu',
            'article/sort',
            'attribute/edit',
            'attribute/index',
            'authmanager/category',
            'authmanager/editgroup',
            'authmanager/group',
            'authmanager/managergroup',
            'authmanager/tree',
            'authmanager/user',
            'authmanager/index',
            'category/edit',
            'category/index',
            'category/operate',
            'category/tree',
            'channel/edit',
            'channel/index',
            'channel/sort',
            'config/edit',
            'config/group',
            'config/index',
            'config/sort',
            'datebase/export',
            'datebase/import',
            'index/index',
            'menu/edit',
            'menu/import',
            'menu/index',
            'menu/sort',
            'model/add',
            'model/edit',
            'model/generate',
            'model/index',
            'public/base',
            'public/error',
            'public/exception',
            'public/login',
            'public/success',
            'qiniu/index',
            'think/add',
            'think/edit',
            'think/lists',
            'update/lists',
            'user/lists',
            'user/add',
            'user/editaction',
            'user/index',
            'user/updatenickname',
            'user/updatepassword',
        ],
    ],
    'common'   => [
        '__file__'   => ['tags.php', 'config.php', 'common.php'],
        '__dir__'    => ['behavior', 'api', 'controller', 'model'],
        'api'        => ['CategoryApi', 'ConfigApi', 'DocumentApi', 'ModelApi', 'SystemApi', 'UserApi'],
        'behavior'   => ['InitHook'],
        'controller' => ['addon'],
        'model'      => ['tree'],
    ],
    'home'     => [
        '__file__'   => ['tags.php', 'config.php', 'common.php'],
        '__dir__'    => ['behavior', 'api', 'controller', 'model'],
        'controller' => ['Addons', 'Article', 'Empty', 'File', 'Home', 'Index', 'User'],
        'logic'      => ['Article', 'Base', 'Download'],
        'model'      => ['Category', 'Channel', 'Document', 'File', 'Member'],
        'view'       => [
            'article/index',
            'article/lists',
            'article/article/detail',
            'article/download/detail',
            'base/common',
            'category/lists',
            'index/index',
            'public/body',
            'public/footer',
            'public/head',
            'public/header',
            'public/var',
            'user/login',
            'user/profile',
            'user/register',
            'widget/categorywidget',
        ],
    ],
    // 。。。 其他更多的模块定义
];
